### ISSUE TITLE
Use Graffiti without io.js

### ISSUE THREAD

**Issue by DrMabuse23** [RisingStack/graffiti#8]
Hi i get some trouble to get graffiti started with node 
`````
node_modules/@risingstack/graffiti/src/koa/index.js:14
    return function *(next) {
                    ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
`````

Here is my Solution

`````
var graffiti = require('@risingstack/graffiti/src/hapi');
var graffitiMongoose = require('@risingstack/graffiti-mongoose');
var HapiReactViews = require('hapi-react-views');
var Path = require('path');

import User from './api/models/user';
import DbConnector from './api/dbconnector';

let connector = new DbConnector();
var server = new Hapi.Server();

server.connection({
  host: '0.0.0.0',
  port: 8000
});
server.register({
  register: graffiti.create(),
  options: {
    adapter: graffitiMongoose,
    models: [User]
  }
}, {
  routes: {
    prefix: '/graphql'
  }
}, function (err) {
  if (err) {
    console.error('Failed to load plugin graffiti :', err);
  }
});
````

**Comment by gergelyke** [comment]
which node version are you using?

**Comment by DrMabuse23** [comment]
0.12.7

**Comment by gergelyke** [comment]
could you try running with `--harmony`?

**Comment by DrMabuse23** [comment]
not at the mom will try later

**Comment by DrMabuse23** [comment]
?

**Comment by gergelyke** [comment]
ops, sorry, wrong button :)

**Comment by hardchor** [comment]
I've never had much luck with the harmony flag and generators (even up to node 5.0.0). The easiest way is probably to transpile it with babel (or use babel-node directly if this isn't a production app).
